config/routes.rb
Demo::Application.routes.draw do
  resources :gynecologic_examinations

end

app/models/gynecologic_examination.rb
class GynecologicExamination < ActiveRecord::Base
  belongs_to :left_ovary, :class_name => 'GynecologicExamination::Ovary', :dependent => :destroy
  belongs_to :ovaries
  accepts_nested_attributes_for :left_ovary, :allow_destroy => true
  attr_accessible :uterine_length
  attr_accessible :left_ovary_id, :left_ovary
  attr_accessible :left_ovary_attributes
end

app/models/gynecologic_examination/ovary.rb
class GynecologicExamination::Ovary < ActiveRecord::Base
  has_one :gynecologic_examination
  has_many :formations, :class_name => 'GynecologicExamination::Ovary::Formation', :dependent => :destroy
  accepts_nested_attributes_for :formations, :allow_destroy => true
  attr_accessible :length
  attr_accessible :formations_attributes
end

app/models/gynecologic_examination/ovary/formation.rb
class GynecologicExamination::Ovary::Formation < ActiveRecord::Base
  belongs_to :ovary
  has_many :chambers, :class_name => 'GynecologicExamination::Ovary::Formation::Chamber', :dependent => :destroy
  accepts_nested_attributes_for :chambers, :allow_destroy => true
  attr_accessible :size
  attr_accessible :chambers_attributes
end

app/models/gynecologic_examination/ovary/formation/chamber.rb
class GynecologicExamination::Ovary::Formation::Chamber < ActiveRecord::Base
  belongs_to :formation
  attr_accessible :size
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gynecologic_examinations_controller.rb
# encoding: UTF-8
class GynecologicExaminationsController < ApplicationController
  # GET /gynecologic_examinations
  # GET /gynecologic_examinations.json
  def index
    @gyn_exams = GynecologicExamination.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gyn_exams }
    end
  end

  # GET /gynecologic_examinations/1
  # GET /gynecologic_examinations/1.json
  def show
    @gyn_exam = GynecologicExamination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gyn_exam }
    end
  end

  # GET /gynecologic_examinations/new
  # GET /gynecologic_examinations/new.json
  def new
    @gyn_exam = GynecologicExamination.new
    @gyn_exam.build_left_ovary

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gyn_exam }
    end
  end

  # GET /gynecologic_examinations/1/edit
  def edit
    @gyn_exam = GynecologicExamination.find(params[:id])
  end

  # POST /gynecologic_examinations
  # POST /gynecologic_examinations.json
  def create
    @gyn_exam = GynecologicExamination.new(params[:gynecologic_examination])
    respond_to do |format|
      if @gyn_exam.save
        format.html { redirect_to @gyn_exam, notice: 'Gynecologic examination successfully created.' }
        format.json { render json: @gyn_exam, status: :created, location: @gyn_exam }
      else
        format.html { render action: "new" }
        format.json { render json: @gyn_exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gynecologic_examinations/1
  # PUT /gynecologic_examinations/1.json
  def update
    @gyn_exam = GynecologicExamination.find(params[:id])

    respond_to do |format|
      if @gyn_exam.update_attributes(params[:gynecologic_examination])
        format.html { redirect_to @gyn_exam, notice: 'Gynecologic examination successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gyn_exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gynecologic_examinations/1
  # DELETE /gynecologic_examinations/1.json
  def destroy
    @gyn_exam = GynecologicExamination.find(params[:id])
    @gyn_exam.destroy

    respond_to do |format|
      format.html { redirect_to gynecologic_examinations_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gynecologic_examinations/_form.html.erb
<%= nested_form_for(@gyn_exam) do |f| %>
  <% if @gyn_exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gyn_exam.errors.count, "error") %> prohibited this gynecologic_examination from being saved:</h2>

      <ul>
      <% @gyn_exam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="fields">
    <span class="on_one_line">
      <%= f.label :uterine_length %><br />
      <%= f.number_field :uterine_length, :style => "width:50px;", :step => "any" %>
    </span>
  </div>
  <fieldset>
    <legend>Left ovary</legend>
    <%= f.fields_for :left_ovary do |builder| %>
      <%= render "ovary_form", :f => builder %>
    <% end %>
  </fieldset>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gynecologic_examinations/_ovary.html.erb
<div class="fields">
  <span class="on_one_line">
    <%= f.label :length %><br />
    <%= f.number_field :length, :style => "width:50px;", :step => "any" %>
  </span>
  <span class="on_one_line">
    <%= f.label :thickness %><br />
    <%= f.number_field :thickness, :style => "width:50px;", :step => "any" %>
  </span>
  <span class="on_one_line">
    <%= f.label :width %><br />
    <%= f.number_field :width, :style => "width:50px;", :step => "any" %>
  </span>
</div>
<div class="fields">
  Образования:
  <%= f.fields_for :formations do |builder| %>
    <span class="on_one_line">
      <%= builder.label :size %><br />
      <%= builder.number_field :size, :style => "width:50px;", :step => "any" %>
    </span>
    <span class="on_one_line"><br />
      <%= f.link_to_remove "Удалить" %>
    </span>
    <div class="fields">
      <%= builder.fields_for :chambers do |ch| %>
        <span class="on_one_line">&nbsp;&nbsp;&nbsp;&nbsp;
        </span>
        <span class="on_one_line">
          <%= ch.label :size %><br />
          <%= ch.number_field :size, :style => "width:50px;", :step => "any" %>
        </span>
        <span class="on_one_line"><br />
          <%= ch.link_to_remove "Удалить" %>
        </span>
      <% end %>
      <%= builder.link_to_add "Добавить камеру", :chambers %>
    </div>
  <% end %>
  <%= f.link_to_add "Добавить образование", :formations %>
</div>

app/views/gynecologic_examinations/_ovary_display.html.erb
<p>
  <%= orientation %> ovary.<br />
  Length <%= ovary.length %> мм.<br />

  Formations:<br />
  <% ovary.formations.each do |formation| %>
    &bull; Size <%= formation.size %> mm<br />
    <% formation.chambers.each do |chamber| %>
      &#9;&#9; Chamber size <%= chamber.size %><br />
    <% end %>
  <% end %>
</p>

app/views/gynecologic_examinations/_ovary_form.html.erb
<div class="fields">
  <span class="on_one_line">
    <%= f.label :length %><br />
    <%= f.number_field :length, :style => "width:50px;", :step => "any" %>
  </span>
</div>
<div class="fields">
  Formations:
  <%= f.fields_for :formations do |builder| %>
    <span class="on_one_line">
      <%= builder.label :size %><br />
      <%= builder.number_field :size, :style => "width:50px;", :step => "any" %>
    </span>
    <span class="on_one_line"><br />
      <%= f.link_to_remove "Remove" %>
    </span>
    <div class="fields">
      <%= builder.fields_for :chambers do |ch| %>
        <span class="on_one_line">&nbsp;&nbsp;&nbsp;&nbsp;
        </span>
        <span class="on_one_line">
          <%= ch.label :size %><br />
          <%= ch.number_field :size, :style => "width:50px;", :step => "any" %>
        </span>
        <span class="on_one_line"><br />
          <%= ch.link_to_remove "Remove" %>
        </span>
      <% end %>
      <%= builder.link_to_add "Add a chamber", :chambers %>
    </div>
  <% end %>
  <%= f.link_to_add "Add a formation", :formations %>
</div>

app/views/gynecologic_examinations/edit.html.erb
<h1>Edit gynecologic examination</h1>

<%= render 'form' %>

<%= link_to 'Show', @gyn_exam %> |
<%= link_to 'Back', gynecologic_examinations_path %>

app/views/gynecologic_examinations/index.html.erb
<h1>List of gynecologic examinations</h1>

<table>
  <tr>
    <th>Uterine length</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gyn_exams.each do |gyn_exam| %>
  <tr>
    <td><%= gyn_exam.uterine_length %></td>
    <td><%= link_to 'Show', gyn_exam %></td>
    <td><%= link_to 'Edit', edit_gynecologic_examination_path(gyn_exam) %></td>
    <td><%= link_to 'Destroy', gyn_exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gynecologic examination', new_gynecologic_examination_path %>

app/views/gynecologic_examinations/new.html.erb
<h1>Gynecologic examination</h1>

<%= render 'form' %>

<%= link_to 'Back', gynecologic_examinations_path %>

app/views/gynecologic_examinations/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  Uterine length: <%= @gyn_exam.uterine_length %><br />
</p>

<%= render :partial => "ovary_display", :locals => { :ovary => @gyn_exam.left_ovary, :orientation => "Left" } %>

<p class="noprint">
  <%= link_to 'Edit', edit_gynecologic_examination_path(@gyn_exam) %> |
  <%= link_to 'Delete', @gyn_exam, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag "application", :media => "screen, projection" %>
  <%= stylesheet_link_tag "print",       :media => "print" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>